<a href="https://colab.research.google.com/github/mariamoiuonalsoud/CodeAlpha_Titanic_Classification/blob/main/Titanic_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#dataset @ https://www.kaggle.com/competitions/titanic/data

# **Creating the train set**

In [81]:
import pandas as pd
train_pd = pd.read_csv('train.csv')
train_pd

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [82]:
#we will use Survived, Pclass, Sex, Age, SibSp, Parch, Fare, and Embarked
train_pd= train_pd[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
train_pd

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [83]:
#to remove NaN data
train_pd = train_pd.dropna()
train_pd

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
885         0       3  female  39.0      0      5  29.1250        Q
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[712 rows x 8 columns]

In [84]:
train_pd.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  712.000000  712.000000  712.000000  712.000000  712.000000  712.000000
mean     0.404494    2.240169   29.642093    0.514045    0.432584   34.567251
std      0.491139    0.836854   14.492933    0.930692    0.854181   52.938648
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    0.000000    0.000000    8.050000
50%      0.000000    2.000000   28.000000    0.000000    0.000000   15.645850
75%      1.000000    3.000000   38.000000    1.000000    1.000000   33.000000
max      1.000000    3.000000   80.000000    5.000000    6.000000  512.329200

# **Data Conversion**
**Pclass:**
*   1-> [1,0,0]
*   2-> [0,1,0]
*   3-> [0,0,1]

**Sex:**
*   male-> 0
*   female-> 1





In [85]:
import numpy as np
from tensorflow.keras.utils import to_categorical
#convert pclass into the categorical form
train_pclass = train_pd['Pclass'].to_numpy()
as_categorical_train_pclass = to_categorical(train_pclass - 1, num_classes=3)
as_categorical_train_pclass

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [86]:
#to convert the sex from string to boolean
def sex_str_to_binary(s):
  if s == 'male':
    return 0
  else:
    return 1

In [87]:
as_binary_train_sex = train_pd['Sex'].apply(sex_str_to_binary).to_numpy()
as_binary_train_sex[:10]

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [88]:
#convert age to numpy array
train_age_np = train_pd['Age'].to_numpy()
#scale the Age values
train_age =(train_age_np-train_pd['Age'].mean()) / train_pd['Age'].std()
train_age[:10]

array([-0.52729787,  0.57668847, -0.25130129,  0.36969103,  0.36969103,
        1.68067481, -1.9072808 , -0.18230214, -1.07929105, -1.76928251])

In [89]:
#convert SibSp to numpy array
train_sibsp_np = train_pd['SibSp'].to_numpy()
#scale the SibSp values
train_sibsp =(train_sibsp_np-train_pd['SibSp'].mean()) / train_pd['SibSp'].std()
train_sibsp[:10]

array([ 0.52214373,  0.52214373, -0.55232545,  0.52214373, -0.55232545,
       -0.55232545,  2.67108207, -0.55232545,  0.52214373,  0.52214373])

In [90]:
#convert Parch to numpy array
train_parch_np = train_pd['Parch'].to_numpy()
#scale the Parch values
train_parch =(train_parch_np-train_pd['Parch'].mean()) / train_pd['Parch'].std()
train_parch[:10]

array([-0.50643136, -0.50643136, -0.50643136, -0.50643136, -0.50643136,
       -0.50643136,  0.66428009,  1.83499154, -0.50643136,  0.66428009])

In [91]:
#convert fare to numpy array
train_fare_np = train_pd['Fare'].to_numpy()
#scale the Fare values
train_fare =(train_fare_np-train_pd['Fare'].mean()) / train_pd['Fare'].std()
train_fare[:10]

array([-0.51601717,  0.69355848, -0.50326656,  0.35007975, -0.50090534,
        0.32670363, -0.25486581, -0.44266244, -0.08493703, -0.33750864])

In [92]:
Y_train = train_pd['Survived'].to_numpy()
Y_train[:10]

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1])

# **Creating the model**

we will ues scikit learns linear model logistic regression to converts all inputs to continuous values and after that we convert the predicting result 0 or 1 to a probability.

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
as_categorical_train_pclass.shape,as_binary_train_sex.reshape(-1, 1).shape

((712, 3), (712, 1))

In [95]:
train_age.shape

(712,)

In [96]:
train_fare.shape

(712,)

In [97]:
train_parch.shape

(712,)

In [98]:
train_sibsp.shape

(712,)

In [99]:
#that is our training dataset
X_train=np.concatenate((as_categorical_train_pclass,
                as_binary_train_sex.reshape(-1, 1),
                train_age.reshape(-1,1),
                train_sibsp.reshape(-1,1),
                train_parch.reshape(-1,1),
                train_fare.reshape(-1,1)),axis=1)
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  0.52214373,
        -0.50643136, -0.51601717],
       [ 1.        ,  0.        ,  0.        , ...,  0.52214373,
        -0.50643136,  0.69355848],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50326656],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.08627442],
       [ 1.        ,  0.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.08627442],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50657227]])

In [100]:
model = LogisticRegression(random_state=0).fit(X_train, Y_train)
model.score(X_train, Y_train)

0.800561797752809

# **Creating the test set**

In [122]:
test_pd = pd.read_csv('test.csv')
test_pd

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [124]:
test_pd=test_pd.fillna(test_pd['Age'].mean())
len(test_pd)

418

In [125]:
test_pd= test_pd[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
test_pd

PassengerId  Pclass     Sex       Age  SibSp  Parch      Fare
0            892       3    male  34.50000      0      0    7.8292
1            893       3  female  47.00000      1      0    7.0000
2            894       2    male  62.00000      0      0    9.6875
3            895       3    male  27.00000      0      0    8.6625
4            896       3  female  22.00000      1      1   12.2875
..           ...     ...     ...       ...    ...    ...       ...
413         1305       3    male  30.27259      0      0    8.0500
414         1306       1  female  39.00000      0      0  108.9000
415         1307       3    male  38.50000      0      0    7.2500
416         1308       3    male  30.27259      0      0    8.0500
417         1309       3    male  30.27259      1      1   22.3583

[418 rows x 7 columns]

In [126]:
test_pclass = test_pd['Pclass'].to_numpy()
as_categorical_test_pclass = to_categorical(test_pclass - 1, num_classes=3)
as_categorical_test_pclass[:10]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [127]:
as_binary_test_sex = test_pd['Sex'].apply(sex_str_to_binary).to_numpy()
as_binary_test_sex[:10]

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [132]:
#convert age to numpy array
test_age_np = test_pd['Age'].to_numpy()
#scale the Age values
test_age =(test_age_np-test_pd['Age'].mean()) / test_pd['Age'].std()
test_age[:10]

array([ 0.33459165,  1.32394352,  2.51116576, -0.25901947, -0.65476022,
       -1.28794542, -0.02157502, -0.33816762, -0.97135282, -0.73390837])

In [133]:
#convert SibSp to numpy array
test_sibsp_np = test_pd['SibSp'].to_numpy()
#scale the SibSp values
test_sibsp =(test_sibsp_np-test_pd['SibSp'].mean()) / test_pd['SibSp'].std()
test_sibsp[:10]

array([-0.49887221,  0.6162539 , -0.49887221, -0.49887221,  0.6162539 ,
       -0.49887221, -0.49887221,  0.6162539 , -0.49887221,  1.73138001])

In [134]:
#convert Parch to numpy array
test_parch_np = test_pd['Parch'].to_numpy()
#scale the Parch values
test_parch =(test_parch_np-test_pd['Parch'].mean()) / test_pd['Parch'].std()
test_parch[:10]

array([-0.39976865, -0.39976865, -0.39976865, -0.39976865,  0.61915388,
       -0.39976865, -0.39976865,  0.61915388, -0.39976865, -0.39976865])

In [135]:
#convert fare to numpy array
test_fare_np = test_pd['Fare'].to_numpy()
#scale the Fare values
test_fare =(test_fare_np-test_pd['Fare'].mean()) / test_pd['Fare'].std()
test_fare[:10]

array([-0.49757564, -0.51242492, -0.46429729, -0.48265295, -0.41773662,
       -0.47257972, -0.50115723, -0.11844997, -0.50832041, -0.20530354])

In [136]:
X_test=np.concatenate((as_categorical_test_pclass,
                as_binary_test_sex.reshape(-1, 1),
                test_age.reshape(-1,1),
                test_sibsp.reshape(-1,1),
                test_parch.reshape(-1,1),
                test_fare.reshape(-1,1)),axis=1)
X_test

array([[ 0.        ,  0.        ,  1.        , ..., -0.49887221,
        -0.39976865, -0.49757564],
       [ 0.        ,  0.        ,  1.        , ...,  0.6162539 ,
        -0.39976865, -0.51242492],
       [ 0.        ,  1.        ,  0.        , ..., -0.49887221,
        -0.39976865, -0.46429729],
       ...,
       [ 0.        ,  0.        ,  1.        , ..., -0.49887221,
        -0.39976865, -0.50794793],
       [ 0.        ,  0.        ,  1.        , ..., -0.49887221,
        -0.39976865, -0.49362157],
       [ 0.        ,  0.        ,  1.        , ...,  0.6162539 ,
         0.61915388, -0.23738922]])

# **Model Predicition**

In [137]:
predictions=model.predict(X_test)
PassengerId=test_pd['PassengerId'].to_numpy()
sub_df=pd.DataFrame({'PassengerId':PassengerId,
                     'Survived':predictions})
sub_df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [138]:
sub_df.to_csv('submission.csv',index=False)

In [74]:
submission_pd = pd.read_csv('gender_submission.csv')
submission_pd

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]